# Generated by Django 3.0.7 on 2020-09-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Image',
        ),
    ]
